title: Achtung! This is attentional style transfer
# logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
show_downloads: true
# google_analytics:
remote_theme: jekyll-theme-minimal
exclude:
  - model
gems:
  -  jekyll-seo-tag
plugins_dir:
  - jekyll-remote-theme 
  - jekyll-feed
  - jekyll-include-cache
# defaults:
#   - scope:
#       path: "assets/js/tfmodel"
